config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"homes#top"
  get "home/about" => "homes#about"
  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: 'followings'
    get "followers" => "relationships#followeds", as: 'followers'
  end

  resources :books, only:[:index, :show, :edit, :create, :destroy, :update] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  
  resources :messages, only:[:create]
  resources :rooms, only:[:show, :create]
  
  get '/searches' => 'searches#search', as: 'search'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable counter_cache: true
  
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}
  
  
  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true, length:{maximum: 140}
  
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entrys, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed

  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower

  has_many :entrys, dependent: :destroy
  has_many :messages, dependent: :destroy

  attachment :profile_image

  validates :name, uniqueness: true, length:{in:2..20}
  validates :introduction, length:{maximum: 50}



  # フォローするメゾット
  def follow(user_id)
    self.follower.create(followed_id: user_id)
  end

  # フォロー外すメゾット
  def unfollow(user_id)
    self.follower.find_by(followed_id: user_id).destroy
  end

  # フォローしているか確認するメゾット
  def following?(user_id)
    self.following_user.include?(user_id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    impressionist :actions => [:show]

    def index
        @book = Book.new
        @books = Book.includes(:favorited_users).sort{|a, b| b.favorited_users.size <=> a.favorited_users.size}
    end

    def show
        @book_new = Book.new
        @book = Book.find(params[:id])
        @book_comment = BookComment.new
        @book_comments = @book.book_comments
        @user = @book.user
        impressionist(@book, nil, unique: [:session_hash.to_s])
    end

    def edit
        @book = Book.find(params[:id])
        if @book.user_id != current_user.id
            redirect_to books_path
        end
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            flash[:notice] = "You have created book successfully."
            redirect_to book_path(@book)
        else
            @books = Book.all
            render :index
        end
    end

    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "You have updated book successfully."
            redirect_to book_path(@book)
        else
            render :edit
        end
    end


    private

    def book_params
        params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def followings
    user = User.find(params[:user_id])
    @users = user.following_user
  end

  def followeds
    user = User.find(params[:user_id])
    @users = user.follower_user
  end



  def create
    current_user.follow(params[:user_id])
    @user = User.find(params[:user_id])

    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def destroy
    current_user.unfollow(params[:user_id])
    @user = User.find(params[:user_id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.create
    @entry1 = Entry.create(user_id: current_user.id, room_id: @room.id)
    @entry2 = Entry.create(entry_room_params)
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entrys = @room.entrys
      @another_entry = @entrys.where.not(user_id: current_user.id).first
    else
      redirect_back fallback_location: root_path
    end
  end



  private
  def entry_room_params
    params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        @book = Book.new
    end

    def show
        @user = User.find(params[:id])
        @book = Book.new
        
        @current_user_entry = Entry.where(user_id: current_user.id)
        @user_entry = Entry.where(user_id: @user.id)
        unless @user.id == current_user.id
            @current_user_entry.each do |cu|
                @user_entry.each do |u|
                    if cu.room_id == u.room_id
                        @is_room = true
                        @room_id = cu.room_id
                    end
                end
            end
            unless @is_room
                @room = Room.new
                @entry = Entry.new
            end
        end
    end

    def edit
        @user = User.find(params[:id])
        if @user.id != current_user.id
            redirect_to user_path(current_user.id)
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "You have updated user successfully."
            redirect_to user_path(@user.id)
        else
            render :edit
        end
    end


    private

    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/relationships/_followed-count.html.erb
<%= link_to user.followed.count, user_followers_path(user)%>

app/views/relationships/_following-count.html.erb
<%= link_to user.follower.count, user_followings_path(user)%>

app/views/relationships/_relationship.html.erb
<% if current_user.following?(user)%>
  <%= link_to user_relationships_path(user), method: :delete, remote: true do %>
    <button class="btn btn-info">フォロー外す</button>
  <% end %>
<% else %>
  <%= link_to user_relationships_path(user), method: :post, remote: true  do %>
    <button class="btn btn-success">フォローする</button>
  <% end %>
<%end%>

app/views/relationships/_relationship_user.html.erb
<% if current_user.following?(user)%>
  <%= link_to 'フォロー解除', user_relationships_path(user), method: :delete, remote: true %>
<% else %>
  <%= link_to 'フォローする',user_relationships_path(user), method: :post, remote: true %>
<% end %>

app/views/relationships/create.js.erb
<!--詳細ページ　いいね機能まとめ-->
$("#user_relationship_<%= @user.id %>").html("<%= j(render 'relationships/relationship', user: @user)%>");
$("#following-count_<%= @user.id%>").html("<%= j(render 'relationships/following-count', user: @user) %>");
$("#followed-count_<%= @user.id%>").html("<%= j(render 'relationships/followed-count', user: @user) %>");

$("#user_chat").html("<%= j(render 'users/chat', user: @user, is_room: @is_room, room: @room, room_id: @room_id, entry: @entry)%>");

<!--ユーザー一覧ページ　いいね機能まとめ-->
$("#user_index_relationship_<%= @user.id%>").html("<%= j(render 'relationships/relationship_user', user: @user)%>");
$(".counting_<%= current_user.id %>").html("<%= j(render 'relationships/following-count', user: current_user)%>");
$("counted_<%= current_user.id %>").html("<%= j(render 'relationships/followed-count', user: current_user)%>");

app/views/relationships/destroy.js.erb
<!--詳細ページ　いいね機能まとめ-->
$("#user_relationship_<%= @user.id %>").html("<%= j(render 'relationships/relationship', user: @user)%>");
$("#following-count_<%= @user.id%>").html("<%= j(render 'relationships/following-count', user: @user) %>");
$("#followed-count_<%= @user.id%>").html("<%= j(render 'relationships/followed-count', user: @user) %>");

$("#user_chat").html('<div></div>');

<!--ユーザー一覧ページ　いいね機能まとめ-->
$("#user_index_relationship_<%= @user.id%>").html("<%= j(render 'relationships/relationship_user', user: @user)%>");
$(".counting_<%= current_user.id %>").html("<%= j(render 'relationships/following-count', user: current_user)%>");
$("counted_<%= current_user.id %>").html("<%= j(render 'relationships/followed-count', user: current_user)%>");

app/views/relationships/followeds.html.erb
<main>
  <h2>Follower Users</h2>
  <% if @users.exists? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">image</th>
          <th scope="col">name</th>
          <th scope="col" colspan = "3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user|%>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill,40,40, format: 'jpeg', fallback: "no-image.jpeg"%></td>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.follower.count %></td>
            <td>フォロワー数: <%= user.followed.count %></td>
           <td><%= link_to 'Show', user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>ユーザーはいません</p>
  <% end %>
</main>

app/views/relationships/followings.html.erb
<main>
  <h2>Follow Users</h2>
  <% if @users.exists? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">image</th>
          <th scope="col">name</th>
          <th scope="col" colspan = "3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user|%>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill,40,40, format: 'jpeg', fallback: "no-image.jpeg"%></td>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.follower.count %></td>
            <td>フォロワー数: <%= user.followed.count %></td>
            <td><%= link_to 'Show', user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>ユーザーはいません</p>
  <% end %>
</main>