config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"homes#top"
  get "home/about" => "homes#about"
  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: 'followings'
    get "followers" => "relationships#followeds", as: 'followers'
  end

  resources :books, only:[:index, :show, :edit, :create, :destroy, :update] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  
  resources :messages, only:[:create]
  resources :rooms, only:[:show, :create]
  
  get '/searches' => 'searches#search', as: 'search'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable counter_cache: true
  
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}
  
  
  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true, length:{maximum: 140}
  
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entrys, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed

  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower

  has_many :entrys, dependent: :destroy
  has_many :messages, dependent: :destroy

  attachment :profile_image

  validates :name, uniqueness: true, length:{in:2..20}
  validates :introduction, length:{maximum: 50}



  # フォローするメゾット
  def follow(user_id)
    self.follower.create(followed_id: user_id)
  end

  # フォロー外すメゾット
  def unfollow(user_id)
    self.follower.find_by(followed_id: user_id).destroy
  end

  # フォローしているか確認するメゾット
  def following?(user_id)
    self.following_user.include?(user_id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    impressionist :actions => [:show]

    def index
        @book = Book.new
        @books = Book.includes(:favorited_users).sort{|a, b| b.favorited_users.size <=> a.favorited_users.size}
    end

    def show
        @book_new = Book.new
        @book = Book.find(params[:id])
        @book_comment = BookComment.new
        @book_comments = @book.book_comments
        @user = @book.user
        impressionist(@book, nil, unique: [:session_hash.to_s])
    end

    def edit
        @book = Book.find(params[:id])
        if @book.user_id != current_user.id
            redirect_to books_path
        end
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            flash[:notice] = "You have created book successfully."
            redirect_to book_path(@book)
        else
            @books = Book.all
            render :index
        end
    end

    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "You have updated book successfully."
            redirect_to book_path(@book)
        else
            render :edit
        end
    end


    private

    def book_params
        params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.create
    @entry1 = Entry.create(user_id: current_user.id, room_id: @room.id)
    @entry2 = Entry.create(entry_room_params)
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entrys = @room.entrys
      @another_entry = @entrys.where.not(user_id: current_user.id).first
    else
      redirect_back fallback_location: root_path
    end
  end



  private
  def entry_room_params
    params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <p class="mx-auto">CopyRight Infratop.inc</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
       <a class="navbar-brand" href="/">Bookers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <%if user_signed_in?%>
              <li>
                <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class:"nav-link text-light" do %>
                <i class="fas fa-users"></i>
                  Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class:"nav-link text-light" do %>
                  <i class="fas fa-book-open"></i>
                  Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do%>
                  <i class="fas fa-sign-out-alt"></i>
                  Log out
                <% end %>
              </li>
            <%else%>
              <li>
                <%= link_to root_path, class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path, class:"nav-link text-light" do %>
                  <i class="fas fa-link"></i>
                  About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i>
                  Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                <% end%>
              </li>
            <%end%>
          </ul>
       </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class = "container mb-3">
  <div class = "row">
    <div class = "col-md-12 text-center">
      <%= form_with url: search_path, method: :get, local: true do |f|%>
        <%= f.text_field :value %>
        <%= f.select :model, [["User", "user"], ["Book", "book"]] %>
        <%= f.select :how, [["完全一致", "match"], ["前方一致", "forward"], ["後方一致", "backword"], ["部分一致","partical"]]%>
        <%= f.submit '検索' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header'%>
  <main>
    <p id="notice"><%= notice%></p>
    <%= yield %>
  </main>
    <%= render 'layouts/footer'%>
  </body>
</html>